[pytest]
markers =
    positive: Тесты на успешные сценарии (валидные данные)
    negative: Тесты на сценарии с ошибками (невалидные данные)

addopts = -v --alluredir=allure-results

testpaths =
    tests